#ifndef DEFINES_H
#define DEFINES_H

#define COMPARE_STEP 50
#define GREEN_LED_PORT	GPIOC
#define GREEN_LED	GPIO13
#define RED_LED_PORT	GPIOB
#define RED_LED		GPIO13
#define YELLOW_LED_PORT GPIOB
#define YELLOW_LED	GPIO12
#define DEBUGVAL	GPIOB_CRL 

#define GAS_PIN		GPIO10
#define GAS_PORT	GPIOB

#define WELD_PIN	GPIO11
#define WELD_PORT	GPIOB

#define BREAK_PIN	GPIO6
#define BREAK_PORT	GPIOB
#endif
